In [22]:
from numpy import exp,array,random,dot

In [39]:
class NeuralNetwork:
    def __init__(self):
        random.seed(1)
        self.weights = 2 * random.random((3,1)) - 1
        
    @staticmethod
    def _sigmoid_derivative(x):
        return NeuralNetwork._sigmoid(x) * (1 - NeuralNetwork._sigmoid(x))

    @staticmethod
    def _sigmoid(x):
        return 1 / (1 + exp(-x))
    
    def predict(self, inputs):
        return self._sigmoid(dot(inputs, self.weights))
    
    def train(self, train_inputs, train_outputs, iterations):
        for i in range(iterations):
            output = self.predict(train_inputs)
            error = train_outputs - output
            adjustments = dot(train_inputs.T, error * self._sigmoid_derivative(output))
            self.weights += adjustments

In [56]:
training_set_inputs = array([[0,0,1], [1,1,1], [1,0,1], [0,1,1], [0,0,0]])
training_set_outputs = array([[0,1,1,0, 0]]).T
iterations = 100000

nn = NeuralNetwork()

print('\ninitial weights: ', nn.weights)

nn.train(train_inputs=training_set_inputs, train_outputs=training_set_outputs, iterations=iterations)
print('\nadjusted weights: ', nn.weights)


initial weights:  [[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]

adjusted weights:  [[19.64772187]
 [-0.40556114]
 [-9.53843554]]


In [57]:
nn.predict(array([0,0,0]))

array([0.5])

In [15]:
2 * random.random((3,1)) -1

array([[-0.39533485],
       [-0.70648822],
       [-0.81532281]])

In [16]:
nn.weights

array([[12.00870061],
       [-0.2044116 ],
       [-5.8002822 ]])

In [19]:
input = array([1,0,0])
input

array([1, 0, 0])

In [ ]:
2 * random.random((3,1)) -1

In [20]:
dot(input, nn.weights)

array([12.00870061])

In [21]:
nn._sigmoid(dot(input, nn.weights))

array([0.99999391])

In [27]:
nn._sigmoid_derivative(dot(input, nn.weights))

array([2.93158719e-09])