In [1]:
from numpy import exp,array,random,dot

In [28]:
class NeuralNetwork:
    def __init__(self):
        random.seed(1)
        self.weights = 2 * random.random((3,1)) -1
        
    @staticmethod
    def _sigmoid_derivative(x):
        return x * (1 - x)

    @staticmethod
    def _sigmoid(x):
        return 1 / (1 + exp(-x))
    
    def predict(self, inputs):
        return self._sigmoid(dot(inputs, self.weights))
    
    def train(self, train_inputs, train_outputs, iterations):
        for i in range(iterations):
            output = self.predict(train_inputs)
            print(output)
            error = train_outputs - output
            print(output)
            adjustments = dot(train_inputs.T, error * self._sigmoid_derivative(output))
            self.weights += adjustments

In [19]:
random.seed(1)
weights = 2 * random.random((3,1)) -1
inputs = array([[1,1,0], [2,1,0]])
dot(inputs, weights)


array([[ 0.274693  ],
       [ 0.10873701]])

In [20]:
NeuralNetwork._sigmoid(dot(inputs, weights))

array([[ 0.56824466],
       [ 0.5271575 ]])

In [34]:
training_set_inputs = array([[0,0,1], [1,1,1], [1,0,1], [0,1,1]])
training_set_outputs = array([[0,1,1,0]]).T
iterations = 3

nn = NeuralNetwork()

print('12123!!', nn.weights)

nn.train(train_inputs=training_set_inputs, train_outputs=training_set_outputs, iterations=iterations)
print(nn.weights)


12123!! [[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
[[ 0.2689864 ]
 [ 0.3262757 ]
 [ 0.23762817]
 [ 0.36375058]]
[[ 0.2689864 ]
 [ 0.3262757 ]
 [ 0.23762817]
 [ 0.36375058]]
[[ 0.29929909]
 [ 0.44378327]
 [ 0.32511054]
 [ 0.41433436]]
[[ 0.29929909]
 [ 0.44378327]
 [ 0.32511054]
 [ 0.41433436]]
[[ 0.32550793]
 [ 0.55437725]
 [ 0.41995875]
 [ 0.45332188]]
[[ 0.32550793]
 [ 0.55437725]
 [ 0.41995875]
 [ 0.45332188]]
[[ 0.65701265]
 [ 0.53906065]
 [-0.66099969]]


In [35]:
print('test')

test
